# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartDroneiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartDroneiOS
  pod 'SwiftSocket', :git => 'https://github.com/swiftsocket/SwiftSocket', :tag => '2.1.0'

end
